macos fix
Signed-off-by: Cody Confer <cody.confer@grafana.com>

diff --git a/home/dot_local/bin/executable_sauce-power b/home/dot_local/bin/executable_sauce-power
--- a/home/dot_local/bin/executable_sauce-power
+++ b/home/dot_local/bin/executable_sauce-power
@@ -182,6 +182,8 @@ cleanup() {
         pkill -P "$EVENTS_PID" 2>/dev/null
         kill "$EVENTS_PID" 2>/dev/null
     fi
+    [ -n "${EVENTS_FIFO:-}" ] && rm -f "$EVENTS_FIFO"
+    return 0
 }
 
 cmd_daemon() {
@@ -196,10 +198,18 @@ cmd_daemon() {
     trap cleanup EXIT INT TERM
     reconcile
 
-    coproc EVENTS { events; }
-    while read -r _ <&"${EVENTS[0]}"; do
+    EVENTS_FIFO="$(mktemp -u "${XDG_RUNTIME_DIR:-/tmp}/sauce-power-events.XXXXXX")"
+    mkfifo -m 600 "$EVENTS_FIFO" || die "unable to create event fifo at $EVENTS_FIFO."
+    events >"$EVENTS_FIFO" &
+    EVENTS_PID=$!
+    exec 3<"$EVENTS_FIFO"
+    rm -f "$EVENTS_FIFO"
+    EVENTS_FIFO=""
+
+    while read -r _ <&3; do
         reconcile
     done
+    exec 3<&-
 }
 
 cmd_button() {
